name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        platform: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint
      if: ${{ matrix.python-version == '3.9' && matrix.platform == 'ubuntu-latest' }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
        make format-check
    - name: Mac testing
      if: ${{ matrix.platform == 'macos-latest' }}
      run: |
        python -m unittest
    - name: Linux testing
      if: ${{ matrix.platform == 'ubuntu-latest' }}
      run: |
        fallocate -l50MiB backing
        /sbin/mkfs.ext4 backing
        mkdir -p test_fs
        mount -t ext4 -o loop,noatime,user_xattr backing test_fs
        TMPDIR=`pwd`/test_fs python -m unittest
