name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        platform: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements_dev.txt
    - name: Lint
      run: |
        make format-check
    - name: Test with pytest
      run: |
        python -m unittest
